package datasources

// inventoryCollectors declares the twenty per-instance collector inventories
// served by the generic data source in inventory.go.
//
// The field tables are transcribed from the API's OpenAPI schemas. Two rules
// govern them and both come straight from the endpoints' own contracts:
//
//   - A nullable column stays nullable here. Null is not zero on these
//     surfaces -- a null scrub_errors is "nobody has ever checked", a null
//     vulnerability_count is "never scanned", a null oom_kill_count is "cgroup
//     v1 cannot see it" -- and collapsing any of them to 0 turns an absence of
//     data into a clean bill of health.
//   - Rows the product hides are still returned. QEMU tombstones, stale
//     Proxmox rows and loopback sockets are listed and flagged rather than
//     filtered, because a sync that cannot see them cannot reconcile them.
var inventoryCollectors = []inventoryCollector{
	{
		name: "systemd_units",
		desc: "The per-unit health rows behind the instance's Services tab -- which units are failed, what systemd's own verdict was, and the journal tail captured at the moment each one broke. A metrics query can say HOW MANY units are failed; only this can name them.\n\nThe cgroup readings (`memory_current`, `cpu_usec`, `oom_kill_count`) are null when unavailable on the host, never 0 -- cgroup v1 has no OOM counter at all, and a 0 there would read as \"nothing was OOM killed\" when the truth is \"we cannot see whether anything was\". `reverse_deps` is null when the host's systemd is too old to report them, which is a different fact from `[]` (\"nothing depends on this unit\").",
		filters: []inventoryFilter{
			{name: "updated_since", kind: fieldString, desc: "Return only rows whose `updated_at` is at or after this ISO 8601 timestamp. Inclusive, so a row updated in the same instant as the cursor comes back rather than falling through the gap. The ingester touches `updated_at` on every agent tick, so this is a freshness filter rather than a change feed, and there are no tombstones: a row the agent stops reporting is deleted."},
			{name: "stale", kind: fieldBool, desc: "Freshness filter over the collector's 10-minute sync window. `false` returns only rows the agent refreshed inside it -- the set you may read as CURRENT state; `true` returns the rest. The two values partition the collection (a row that never synced counts as stale). Omit for both."},
			{name: "active_state", kind: fieldString, desc: "Filter by systemd's own ActiveState -- `failed` is the on-call filter. The column stores whatever systemd reported, verbatim; a state outside the documented list is still returned, it just cannot be selected by name. One of: `active`, `reloading`, `inactive`, `failed`, `activating`, `deactivating`, `maintenance`, `refreshing`.", oneOf: []string{"active", "reloading", "inactive", "failed", "activating", "deactivating", "maintenance", "refreshing"}},
			{name: "q", kind: fieldString, desc: "Case-insensitive substring match on the unit name."},
		},
		fields: []inventoryField{
			{"id", fieldInt, "Row identifier."},
			{"host_id", fieldString, "The instance (host) UUID this row belongs to."},
			{"name", fieldString, "The unit name, e.g. `nginx.service`. This is the row identity."},
			{"load_state", fieldString, "systemd's LoadState -- whether the unit file itself loaded (`loaded`, `not-found`, `masked`). Null when not reported."},
			{"active_state", fieldString, "systemd's ActiveState, verbatim."},
			{"sub_state", fieldString, "systemd's SubState, the unit-type-specific detail behind `active_state` (e.g. `running`, `dead`, `failed`). Null when not reported."},
			{"unit_file_state", fieldString, "Whether the unit is enabled at boot (`enabled`, `disabled`, `static`, `masked`). Null when not reported."},
			{"result", fieldString, "systemd's own verdict on the last run."},
			{"failed", fieldBool, "Whether systemd currently reports the unit as failed. The on-call signal."},
			{"n_restarts", fieldInt, "systemd's NRestarts counter for the unit. **Null means unavailable, not 0.**"},
			{"active_enter_at", fieldString, "When the unit last entered its active state. Null when systemd recorded no such transition."},
			{"inactive_enter_at", fieldString, "When the unit last entered its inactive state. Null when systemd recorded no such transition."},
			{"since_at", fieldString, "When the CURRENT state began -- `active_enter_at` for a running unit, `inactive_enter_at` otherwise. Null when systemd recorded no transition."},
			{"memory_current", fieldInt, "Bytes. **Null means unavailable on this host, not 0.**"},
			{"cpu_usec", fieldInt, "Microseconds of CPU since unit start. **Null means unavailable, not 0.**"},
			{"oom_kill_count", fieldInt, "Kills since the unit started (the raw cgroup counter; the cgroup directory is recreated on restart). **Null means unavailable** -- cgroup v1 has no such counter -- and must not be read as \"nothing was OOM killed\"."},
			{"journal_tail", fieldStringList, "Error-priority journal lines captured ONCE, at the moment the unit failed, and then kept. The ingester deliberately never clears these columns, so a unit that failed and later RECOVERED still carries the journal from that failure: a row can read `failed: false` / `active_state: active` and a non-empty `journal_tail` at the same time. Always read it against `drilldown_at` (when it was captured) and `active_state` (what the unit is doing now) -- it is last-failure evidence, not a statement about the current state. Empty only for a unit that has never failed."},
			{"reverse_deps", fieldStringList, "What depends on this unit. **Null means the host's systemd is too old to report them** (< 230) -- a different fact from `[]`, which means nothing depends on it."},
			{"drilldown_at", fieldString, "When `journal_tail` / `reverse_deps` were captured."},
			{"last_synced_at", fieldString, "Server arrival time of the tick that last refreshed this row (never the agent's clock)."},
			{"stale", fieldBool, "True when the agent has not refreshed this row inside the 10-minute window. A stale row is a LAST KNOWN state, not a current one."},
			{"created_at", fieldString, "When this row was first recorded. This is when the agent first happened to report it, not anything an operator would recognize."},
			{"updated_at", fieldString, "When this row was last written. The ingester touches it on every agent tick, so it is a freshness stamp rather than a change feed."},
		},
	},
	{
		name: "docker_containers",
		desc: "The per-container state rows behind the instance's Containers tab -- which container is restart-looping, what it exited with, and whether the kernel OOM-killed it.\n\nA row is keyed by container NAME, the durable identity: a `docker compose up` recreate mints a new `container_id` and keeps the name. `health` is null when the image defines no HEALTHCHECK -- not applicable, never a passing verdict -- and `restarts_last_24h` counts genuine crash-restarts only, since a manual `docker restart` does not bump the daemon's counter.\n\nContainer rows need agent >= 1.11.2. On an older agent the list is empty and `collector.supported` is false -- check it before reading an empty list as \"no containers\".",
		filters: []inventoryFilter{
			{name: "updated_since", kind: fieldString, desc: "Return only rows whose `updated_at` is at or after this ISO 8601 timestamp. Inclusive, so a row updated in the same instant as the cursor comes back rather than falling through the gap. The ingester touches `updated_at` on every agent tick, so this is a freshness filter rather than a change feed, and there are no tombstones: a row the agent stops reporting is deleted."},
			{name: "stale", kind: fieldBool, desc: "Freshness filter over the collector's 10-minute sync window. `false` returns only rows the agent refreshed inside it -- the set you may read as CURRENT state; `true` returns the rest. The two values partition the collection (a row that never synced counts as stale). Omit for both."},
			{name: "status", kind: fieldString, desc: "Filter by the container's lifecycle state, in the `docker inspect` State.Status vocabulary. One of: `unknown`, `created`, `running`, `paused`, `restarting`, `removing`, `exited`, `dead`.", oneOf: []string{"unknown", "created", "running", "paused", "restarting", "removing", "exited", "dead"}},
			{name: "health", kind: fieldString, desc: "Filter by HEALTHCHECK verdict. `none` selects the containers whose image defines no HEALTHCHECK -- a real, distinct state that the row carries as a null `health`, and one that neither `healthy` nor `unhealthy` would return. One of: `starting`, `healthy`, `unhealthy`, `none`.", oneOf: []string{"starting", "healthy", "unhealthy", "none"}},
			{name: "q", kind: fieldString, desc: "Case-insensitive substring match on the container name or its image."},
		},
		fields: []inventoryField{
			{"id", fieldInt, "Row identifier."},
			{"host_id", fieldString, "The instance (host) UUID this row belongs to."},
			{"name", fieldString, "The container name. This is the durable identity: a `docker compose up` recreate mints a new `container_id` and keeps the name, so the row follows the name."},
			{"container_id", fieldString, "The runtime id, which CHANGES on a recreate. `name` is the stable key."},
			{"image", fieldString, "The image reference the container was started from, e.g. `nginx:1.27`. Null when not reported."},
			{"image_id", fieldString, "The `sha256:` config digest, for joining to image-level findings."},
			{"status", fieldString, "The container's lifecycle state, in the `docker inspect` State.Status vocabulary, stored verbatim. `unknown` is what a value outside the pinned contract normalizes to. One of: `unknown`, `created`, `running`, `paused`, `restarting`, `removing`, `exited`, `dead`."},
			{"health", fieldString, "HEALTHCHECK verdict. **Null means the image defines no HEALTHCHECK** -- not-applicable, never a passing result. One of: `starting`, `healthy`, `unhealthy`."},
			{"state_detail", fieldString, "Human summary, e.g. `exited (code 137, OOM killed)`."},
			{"exit_code", fieldInt, "Null for a container that never exited -- not the same as exit code 0."},
			{"oom_killed", fieldBool, "Whether the kernel OOM-killed the container on its last exit."},
			{"restart_count", fieldInt, "The daemon's cumulative RestartCount."},
			{"restarts_last_24h", fieldInt, "Restart-policy restarts in the trailing 24 hours -- the restart-loop signal. Counted from genuine crash-restarts only: a manual `docker restart` does not bump the daemon's counter. **A FLOOR, not an exact count, for a sustained loop:** the ingester keeps at most the 100 most recent increment events per container, so a container restarting every minute for a day reports roughly the last 100 of them. Treat a high value as \"at least this many\"; it is the same number the dashboard shows."},
			{"started_at", fieldString, "When the container last started. Null for one that never has."},
			{"finished_at", fieldString, "When the container last exited. Null for one that never has -- not the same as \"exited just now\"."},
			{"cpu_percent", fieldFloat, "CPU use at the last tick. **Null means no sample, not idle.**"},
			{"memory_usage", fieldInt, "Bytes."},
			{"memory_limit", fieldInt, "Bytes. Null when the container is unlimited."},
			{"state_changed_at", fieldString, "When `status` last flipped. The field to poll for state transitions."},
			{"last_synced_at", fieldString, "Server arrival time of the tick that last refreshed this row (never the agent's clock). Null when the row has never synced."},
			{"stale", fieldBool, "True when the agent has not refreshed this row inside the 10-minute window."},
			{"created_at", fieldString, "When this row was first recorded. This is when the agent first happened to report it, not anything an operator would recognize."},
			{"updated_at", fieldString, "When this row was last written. The ingester touches it on every agent tick, so it is a freshness stamp rather than a change feed."},
		},
	},
	{
		name: "docker_images",
		desc: "The container images this instance runs, with their scan verdict -- the security posture of what is actually deployed here.\n\nTHE HONESTY CONTRACT: `vulnerability_count` and `critical_vulnerability_count` are **null unless `state` is `scanned`**, and `countable` says which it is. A null is \"not scanned\", never \"clean\" -- the underlying columns are NOT NULL with a default of 0, so publishing them verbatim would report a clean bill of health for an image nobody has ever scanned. `packages_truncated` / `finding_count_is_floor` mark a scan whose package list the agent capped: the findings are real but the count is a FLOOR, so render \"12+\" rather than \"12\".\n\nThis data is organization-scoped underneath. Findings are a property of the IMAGE, so fifty hosts running one digest is one row and one scan; this data source returns the slice this instance runs. `id` therefore identifies an image in your organization, not a per-host row.\n\nThere is no `stale` field here, unlike the sibling collectors. Their `stale` is a 10-minute agent-sync window; this collector's only freshness column is `last_seen_at` against a 30-day reaper, which is a different question by two orders of magnitude.",
		filters: []inventoryFilter{
			{name: "updated_since", kind: fieldString, desc: "Return only rows whose `updated_at` is at or after this ISO 8601 timestamp. Inclusive, so a row updated in the same instant as the cursor comes back rather than falling through the gap. Unlike the host-scoped collectors, this one IS a usable change feed: an image row is only rewritten when something about it actually changes, because `last_seen_at` is refresh-throttled rather than restamped on every agent tick. There are still no tombstones -- an image the reaper drops after 30 days simply stops appearing."},
			{name: "state", kind: fieldString, desc: "Filter by scan verdict. `scanned` is the only state whose counts mean anything; the other three are the states the null-count contract exists for. One of: `pending`, `scanned`, `unsupported`, `unscannable`.", oneOf: []string{"pending", "scanned", "unsupported", "unscannable"}},
			{name: "q", kind: fieldString, desc: "Case-insensitive substring match on any of the image's tags or its digest."},
		},
		fields: []inventoryField{
			{"id", fieldString, "Organization-scoped image row."},
			{"organization_id", fieldInt, "The organization that owns the image row. Findings are a property of the IMAGE, so fifty hosts running one digest share one row and one scan."},
			{"image_id", fieldString, "The sha256: config digest -- the durable, content-addressed identity."},
			{"short_digest", fieldString, "First 12 characters of the digest, without the sha256: prefix."},
			{"display_name", fieldString, "A tag if the image carries one, else the short digest. A label, not an id."},
			{"tags", fieldStringList, "Every tag on the image. May be empty."},
			{"repo_digests", fieldStringList, "Registry digests -- what an operator pastes into `docker pull`."},
			{"distro", fieldString, "The OS the agent detected inside the image."},
			{"ecosystem", fieldString, "The advisory ecosystem the packages were matched against."},
			{"state", fieldString, "The scan verdict, and the field to read BEFORE the counts. Note that `pending` is terminal without the container-image-scanning entitlement (Pro and above): discovery is not plan-gated, so a plan without it collects image rows that are never scanned. `pending` = discovered, inventory not received yet; `scanned` = matched against the advisory data; `unsupported` = no mappable distro or package manager (scratch, distroless), permanent for this digest; `unscannable` = extraction failed."},
			{"state_reason", fieldString, "The human explanation behind a non-scanned state."},
			{"state_error_type", fieldString, "The machine-readable code beside state_reason. Only `api_error` is transient -- the rest are permanent for an immutable digest, so do not retry them."},
			{"countable", fieldBool, "Whether the counts below mean anything at all. False for any non-scanned state."},
			{"vulnerability_count", fieldInt, "NULL unless state is `scanned`. A null is \"not scanned\", never \"zero vulnerabilities\" -- see the honesty contract above."},
			{"critical_vulnerability_count", fieldInt, "NULL unless state is `scanned`."},
			{"packages_truncated", fieldBool, "The agent capped the package list it uploaded."},
			{"finding_count_is_floor", fieldBool, "The counts are a FLOOR rather than a total (a scanned image whose package list was capped). Render \"12+\" rather than \"12\"."},
			{"last_seen_at", fieldString, "Last time a /collect tick reported a container running this image in this organization. The reaper drops rows unseen for 30 days. This is the freshness field for this collector -- there is no `stale` flag."},
			{"inventory_received_at", fieldString, "When the agent last uploaded this image's package list."},
			{"last_scanned_at", fieldString, "When the package list was last matched against the advisory data."},
			{"created_at", fieldString, "When this row was first recorded. This is when the agent first happened to report it, not anything an operator would recognize."},
			{"updated_at", fieldString, "When this row was last written. The ingester touches it on every agent tick, so it is a freshness stamp rather than a change feed."},
		},
	},
	{
		name: "listening_ports",
		desc: "What is listening on this instance, and on which address -- where an audit or a CMDB reconciliation starts, and the one collector surface with no metric series at all.\n\nLOOPBACK SOCKETS ARE RETURNED, flagged `loopback = true`. The dashboard hides them as noise; a data source that did the same would make \"bound to loopback only\" indistinguishable from \"not listening\", and those are opposite conclusions in a security review. Set `loopback = false` for the externally-reachable set.\n\nThese are SNAPSHOT ENTRIES, not rows: the data is a JSON array rewritten whole on every agent tick, so there is no `updated_since` cursor and no stable id -- only the natural key (port + protocol + address). Use `collector.last_reported_at` for freshness.",
		filters: []inventoryFilter{
			{name: "protocol", kind: fieldString, desc: "Exact, case-insensitive match on the transport protocol, e.g. `tcp`."},
			{name: "loopback", kind: fieldBool, desc: "`false` returns only sockets reachable off the host -- the set a security review cares about. `true` returns only the loopback-bound ones. Omit for both."},
			{name: "q", kind: fieldString, desc: "Case-insensitive substring match on the address, protocol or port."},
		},
		fields: []inventoryField{
			{"port", fieldInt, "The port the socket is bound to. Part of the natural key (port + protocol + address); these entries carry no id."},
			{"protocol", fieldString, "The transport protocol, e.g. `tcp`. Null when the agent did not classify it."},
			{"address", fieldString, "The address the socket is bound to."},
			{"stack", fieldString, "ipv4 / ipv6 / dual-stack, as the agent classified it. Null on an agent that did not."},
			{"loopback", fieldBool, "Bound to a loopback address, so NOT reachable off the host. These entries are returned rather than hidden -- the dashboard hides them, but an API that did would make \"bound to loopback only\" indistinguishable from \"not listening\", which are opposite conclusions in a security review. Filter with `loopback=false` to get only the exposed sockets."},
		},
	},
	{
		name: "smart_devices",
		desc: "smartctl's PASSED / FAILED verdict per drive -- the half of disk health that no metrics query carries. The wear percentage is queryable as `disk_health_percentage`; the VERDICT is state, and a drive can report 100% life remaining and FAILED on the same tick.\n\nA NULL `overall_health` MEANS SMARTCTL GAVE NO VERDICT, not PASSED: a drive behind a RAID controller that passes no SMART through, or a USB bridge that does not implement it. `verdict_known` is published beside it so a `failed = false` never has to carry \"or we could not tell\" -- read it first.\n\nThese are SNAPSHOT ENTRIES, not rows: no stable id and no timestamps. Use `collector.last_reported_at` for freshness.",
		filters: []inventoryFilter{
			{name: "health", kind: fieldString, desc: "THREE values, not two: `unknown` is a real state (smartctl reported no verdict) and a two-valued filter would force it into one of the other buckets. One of: `passed`, `failed`, `unknown`.", oneOf: []string{"passed", "failed", "unknown"}},
			{name: "q", kind: fieldString, desc: "Case-insensitive substring match on the device name."},
		},
		fields: []inventoryField{
			{"device", fieldString, "The device node, e.g. `/dev/sda`. The natural key; these entries carry no id."},
			{"overall_health", fieldString, "smartctl's own word, normalized to PASSED / FAILED where the line was recognized and carried verbatim where it was not. NULL MEANS SMARTCTL GAVE NO VERDICT -- a drive behind a RAID controller that passes no SMART through, or a USB bridge that does not implement it. It does NOT mean PASSED, and that is the one misreading this endpoint exists to prevent."},
			{"verdict_known", fieldBool, "Whether `overall_health` carries a verdict at all. Read this before `failed`: without it, `failed: false` silently means \"healthy, or we could not tell\"."},
			{"failed", fieldBool, "The verdict is FAILED. False when unknown -- see `verdict_known`."},
			{"passed", fieldBool, "The verdict is PASSED. False when unknown -- see `verdict_known`."},
		},
	},
	{
		name: "zfs_pools",
		desc: "The per-pool health rows behind the instance's storage view -- which pool is degraded, how far the resilver got, and what the last scrub found.\n\nTHE NULL-VS-ZERO RULE IS THE POINT of these columns. `scrub_errors` null means unknown (never scrubbed, resilver in progress, or `zpool status` unavailable) while `0` means a scrub completed clean -- reading null as 0 turns \"nobody has ever checked\" into \"verified healthy\". `degraded_vdevs` / `resilver_progress` / `vdev_tree` are null when `zpool status` was unavailable that tick, and `health` may still be present (it comes from `zpool list`), so \"DEGRADED with a null `degraded_vdevs`\" is a real row: degraded, extent unknown.",
		filters: []inventoryFilter{
			{name: "updated_since", kind: fieldString, desc: "Return only rows whose `updated_at` is at or after this ISO 8601 timestamp. Inclusive, so a row updated in the same instant as the cursor comes back rather than falling through the gap. The ingester touches `updated_at` on every agent tick, so this is a freshness filter rather than a change feed, and there are no tombstones: a row the agent stops reporting is deleted."},
			{name: "stale", kind: fieldBool, desc: "Freshness filter over the collector's 10-minute sync window. `false` returns only rows the agent refreshed inside it -- the set you may read as CURRENT state; `true` returns the rest. The two values partition the collection (a row that never synced counts as stale). Omit for both."},
			{name: "health", kind: fieldString, desc: "Filter by the raw zpool health string. One of: `ONLINE`, `DEGRADED`, `FAULTED`, `OFFLINE`, `REMOVED`, `UNAVAIL`, `SUSPENDED`. A state ZFS adds later is still returned unfiltered, it just cannot be selected by name.", oneOf: []string{"ONLINE", "DEGRADED", "FAULTED", "OFFLINE", "REMOVED", "UNAVAIL", "SUSPENDED"}},
			{name: "q", kind: fieldString, desc: "Case-insensitive substring match on the pool name."},
		},
		fields: []inventoryField{
			{"id", fieldInt, "Row identifier."},
			{"host_id", fieldString, "The instance (host) UUID this row belongs to."},
			{"name", fieldString, "The pool name, e.g. `tank`. This is the row identity."},
			{"health", fieldString, "The raw zpool health string, verbatim. Null means the tick carried no health at all -- which is NOT \"ONLINE\". A state ZFS adds later keeps its string here with a null `health_code`."},
			{"health_code", fieldInt, "Stable 0 ONLINE .. 6 SUSPENDED enum. Null when `health` is unrecognized."},
			{"state_detail", fieldString, "Human summary, e.g. `DEGRADED -- resilvering (42.1% done)`."},
			{"problem", fieldBool, "Health present and not ONLINE. A null health reads false: unknown is never a problem signal."},
			{"degraded_vdevs", fieldInt, "Every unhealthy node, intermediate vdevs AND leaves (one faulted disk in a mirror counts 2), so use it as a `> 0` signal, never as \"N disks failed\". **Null means `zpool status` was unavailable this tick**, not zero."},
			{"resilver_progress", fieldFloat, "Percent. `0.0` means BOTH \"not resilvering\" and \"resilver just started, no percent printed yet\" -- only a positive value proves one is running, which is what `resilvering` reports. **Null means `zpool status` was unavailable.**"},
			{"resilvering", fieldBool, "Whether a resilver is running. The authoritative answer: `resilver_progress` reads `0.0` both for \"not resilvering\" and for \"just started, no percent printed yet\"."},
			{"scrub_errors", fieldInt, "**Null means unknown** -- never scrubbed, resilver in progress, or `zpool status` unavailable. `0` means a scrub completed clean. Reading null as 0 turns \"nobody has ever checked\" into \"verified healthy\"."},
			{"scrub_verdict", fieldString, "`clean`, `N errors`, or null when `scrub_errors` is unknown."},
			{"data_errors", fieldString, "The raw `errors:` line from `zpool status`."},
			{"fragmentation", fieldInt, "Percent."},
			{"capacity_percent", fieldInt, "Percent of the pool allocated. **Null means `zpool status` was unavailable**, not 0."},
			{"size_bytes", fieldInt, "Pool size in bytes. **Null means unavailable**, not 0."},
			{"alloc_bytes", fieldInt, "Bytes allocated. **Null means unavailable**, not 0."},
			{"free_bytes", fieldInt, "Bytes free. **Null means unavailable**, not 0."},
			{"dedup_ratio", fieldFloat, "Deduplication ratio. **Null means unavailable**, not 0."},
			{"zfs_version", fieldString, "The ZFS version string the host reported, e.g. `zfs-2.2.2-1`. Null when not reported."},
			{"vdev_tree", fieldJSON, "Scrubbed diagnostic tree -- which vdev or disk is faulted. **Null means `zpool status` was unavailable.** Section devices (logs/cache/spares/special) appear BOTH nested in `children` and in their own section list; that is deliberate, so do not count them twice. JSON-encoded; decode with `jsondecode()`."},
			{"state_changed_at", fieldString, "When `health` last flipped."},
			{"last_synced_at", fieldString, "Server arrival time of the tick that last refreshed this row (never the agent's clock). Null when the row has never synced."},
			{"stale", fieldBool, "True when the agent has not refreshed this row inside the 10-minute window."},
			{"created_at", fieldString, "When this row was first recorded. This is when the agent first happened to report it, not anything an operator would recognize."},
			{"updated_at", fieldString, "When this row was last written. The ingester touches it on every agent tick, so it is a freshness stamp rather than a change feed."},
		},
	},
	{
		name: "raid_arrays",
		desc: "The mdadm arrays on this instance: which one is degraded, which member failed, and how far the rebuild got.\n\nREAD `status`, NOT THE THREE BOOLEANS. mdstat reports a SET of words and an array is routinely several at once, so `healthy` and `degraded` are BOTH true for the normal shape of a degrading array that is still serving. `status` applies the precedence failed > degraded > healthy; an if/else over the booleans reports a degrading array as fine. The raw set is published as `state` because collapsing it loses \"active AND recovering\".\n\nThe progress percentages are null-means-no-such-operation: a 0 in `rebuild_status_percent` would read as a rebuild stuck at the start, the alarming reading of a perfectly healthy array.\n\nTWO THINGS THIS CANNOT TELL YOU. There is no `stale` field or filter -- the product has no RAID freshness window, so publishing a verdict would invent one; compare `last_synced_at` against `collector.last_reported_at` yourself. And an empty list is ambiguous here in a way it is not elsewhere: RAID ingestion cannot distinguish a collection FAILURE from \"this host has no arrays\". Do not treat a single empty read as authoritative for a host you know has arrays.",
		filters: []inventoryFilter{
			{name: "updated_since", kind: fieldString, desc: "Return only rows whose `updated_at` is at or after this ISO 8601 timestamp. Inclusive, so a row updated in the same instant as the cursor comes back rather than falling through the gap. The ingester touches `updated_at` on every agent tick, so this is a freshness filter rather than a change feed, and there are no tombstones: a row the agent stops reporting is deleted."},
			{name: "status", kind: fieldString, desc: "Filter by the precedence verdict (failed > degraded > healthy). One of: `failed`, `degraded`, `healthy`, `unknown`.", oneOf: []string{"failed", "degraded", "healthy", "unknown"}},
			{name: "q", kind: fieldString, desc: "Case-insensitive substring match on the device or array name."},
		},
		fields: []inventoryField{
			{"id", fieldInt, "Row identifier."},
			{"host_id", fieldString, "The instance (host) UUID this row belongs to."},
			{"device", fieldString, "The kernel device, and the identity (the upsert key is host + device)."},
			{"name", fieldString, "mdadm's own array name, which is NOT the device and is often blank."},
			{"uuid", fieldString, "The mdadm array UUID, stable across a device renumbering."},
			{"raid_level", fieldString, "The array's RAID level, e.g. `raid1`. Null when mdadm did not report it."},
			{"state", fieldStringList, "The raw /proc/mdstat word SET, verbatim. An array really can be several at once (\"active\" AND \"degraded\"), which is why this is a list and why collapsing it loses information -- a degrading array that is still serving is a different situation from one that is not."},
			{"status", fieldString, "The collapsed verdict, with precedence failed > degraded > healthy. THIS IS THE FIELD TO BRANCH ON. `unknown` means the state set matched none of them, not that the array is fine. One of: `failed`, `degraded`, `healthy`, `unknown`."},
			{"healthy", fieldBool, "The state set contains \"active\" or \"clean\". DOES NOT PARTITION with the two below: a degraded array that is still serving reads `healthy: true` AND `degraded: true`. An if/else over these three reports a degrading array as fine -- read `status` instead."},
			{"degraded", fieldBool, "The state set contains \"degraded\". See `healthy`."},
			{"failed", fieldBool, "The state set contains \"failed\". See `healthy`."},
			{"active_devices", fieldInt, "Devices mdadm counts as active. Null when not reported, not 0."},
			{"total_devices", fieldInt, "Devices mdadm counts in the array. Null when not reported, not 0."},
			{"failed_devices", fieldInt, "Devices mdadm counts as failed. **Null means not reported, never \"none failed\".**"},
			{"spare_devices", fieldInt, "Devices mdadm counts as spares. Null when not reported, not 0."},
			{"working_devices", fieldInt, "Devices mdadm counts as working. Null when not reported, not 0."},
			{"physical_disks", fieldInt, "How many physical disks mdadm attributes to the array."},
			{"component_devices", fieldStringList, "The member block devices. This is how you find the disk to replace, and the reason this row beats the metric series."},
			{"resync_status", fieldString, "Null unless a resync is in flight."},
			{"resync_status_percent", fieldInt, "Percent complete. NULL MEANS NO RESYNC IS RUNNING -- a 0 would read as a resync stuck at the start."},
			{"check_status", fieldString, "Null unless a scrub/check is in flight."},
			{"check_status_percent", fieldInt, "Percent complete. Null means no check is running -- see `resync_status_percent`."},
			{"rebuild_status", fieldString, "Null unless a rebuild is in flight."},
			{"rebuild_status_percent", fieldInt, "Percent complete. Null means no rebuild is running -- see `resync_status_percent`."},
			{"array_size", fieldString, "mdadm's human string. The numeric twin is `array_size_num`."},
			{"array_size_num", fieldInt, "Bytes."},
			{"used_dev_size", fieldString, "Per-device size as mdadm printed it. Null when not reported."},
			{"used_dev_size_num", fieldInt, "Per-device size in bytes, parsed from `used_dev_size`. Null when unparsed or not reported."},
			{"chunk_size", fieldString, "Chunk size as mdadm printed it, e.g. `512K`. Null when not reported."},
			{"chunk_size_num", fieldInt, "Chunk size in bytes, parsed from `chunk_size`. Null when unparsed or not reported."},
			{"version", fieldString, "The mdadm superblock version."},
			{"persistence", fieldString, "mdadm's superblock persistence line. Null when not reported."},
			{"consistency_policy", fieldString, "mdadm's consistency policy for the array, e.g. `bitmap`. Null when not reported."},
			{"mdadm_version", fieldString, "The mdadm metadata version, e.g. `1.2`. Null when not reported."},
			{"events", fieldString, "mdadm's event counter as printed. Null when not reported."},
			{"events_num", fieldInt, "mdadm's event counter, parsed. Null when unparsed or not reported."},
			{"preferred_minor", fieldInt, "The array's preferred minor device number. Null when not reported."},
			{"creation_time", fieldString, "When mdadm reports the array was created. Null when not reported."},
			{"update_time", fieldString, "When mdadm last updated the array superblock. Null when not reported."},
			{"last_synced_at", fieldString, "When the agent last reported this array. THERE IS NO `stale` FIELD ON THIS COLLECTOR -- the product has no RAID freshness window anywhere, so publishing a verdict here would invent one. Compare this against `collector.last_reported_at` yourself if you need a freshness call."},
			{"created_at", fieldString, "When this row was first recorded. This is when the agent first happened to report it, not anything an operator would recognize."},
			{"updated_at", fieldString, "When this row was last written. The ingester touches it on every agent tick, so it is a freshness stamp rather than a change feed."},
		},
	},
	{
		name: "temperature_sensors",
		desc: "The sensor INVENTORY on this instance -- not the readings. The temperature itself is a metric series (`temperature`, labelled by `sensor_id` and `category`); this is what makes that series legible, turning \"71.0 on coretemp-core-3\" into \"Core 3, critical at 100\". Join the two on `sensor_id`.\n\nNULL THRESHOLDS ARE COMMON AND MEAN \"the chip declares none\" -- not zero, and not \"no limit\". Plenty of drivers expose a reading with no high or critical point at all, and a rule that treats a null as 0 fires on every one of them.\n\nThis collector has no toggle and no version floor: every agent reports the sensors it finds, so `collector.enabled` and `collector.supported` are always true and there is no switch to look for. An empty list means this hardware exposes no sensors. `stale` is an HOUR here, not the ten minutes the per-tick collectors use, because the question is whether the sensor is still present.",
		filters: []inventoryFilter{
			{name: "updated_since", kind: fieldString, desc: "Return only rows whose `updated_at` is at or after this ISO 8601 timestamp. Inclusive, so a row updated in the same instant as the cursor comes back rather than falling through the gap. The ingester touches `updated_at` on every agent tick, so this is a freshness filter rather than a change feed, and there are no tombstones: a row the agent stops reporting is deleted."},
			{name: "category", kind: fieldString, desc: "Filter by subsystem. One of: `cpu`, `gpu`, `storage`, `network`, `chipset`, `other`.", oneOf: []string{"cpu", "gpu", "storage", "network", "chipset", "other"}},
			{name: "stale", kind: fieldBool, desc: "Freshness filter. The window here is an HOUR, not the ten minutes the per-tick collectors use, because the question is whether the sensor is still PRESENT. Omit for both."},
			{name: "q", kind: fieldString, desc: "Case-insensitive substring match on the sensor id or label."},
		},
		fields: []inventoryField{
			{"id", fieldInt, "Row identifier."},
			{"host_id", fieldString, "The instance (host) UUID this row belongs to."},
			{"sensor_id", fieldString, "The identity, and the label the metric series is keyed on. This is the join back to metrics/query for the actual readings."},
			{"sensor_type", fieldString, "The driver or chip reporting it."},
			{"label", fieldString, "The human label the driver supplies. Null is common -- `sensor_id` is always present, this is not."},
			{"category", fieldString, "Which subsystem the sensor belongs to. One of: `cpu`, `gpu`, `storage`, `network`, `chipset`, `other`."},
			{"high_threshold", fieldString, "Degrees Celsius, as the chip declares it. NULL MEANS THE CHIP DECLARES NONE -- not zero, and not \"no limit\". Plenty of drivers expose a reading with no threshold at all."},
			{"critical_threshold", fieldString, "Degrees Celsius. Null means none is declared -- see `high_threshold`."},
			{"last_seen_at", fieldString, "`last_seen_at`, NOT `last_synced_at` -- the column this collector carries, and what `stale` is derived from."},
			{"stale", fieldBool, "The sensor has not been seen for an HOUR -- not the ten minutes every per-tick collector uses. This table is an inventory, so the question is whether the sensor is still PRESENT, and one missed tick does not remove hardware."},
			{"created_at", fieldString, "When this row was first recorded. This is when the agent first happened to report it, not anything an operator would recognize."},
			{"updated_at", fieldString, "When this row was last written. The ingester touches it on every agent tick, so it is a freshness stamp rather than a change feed."},
		},
	},
	{
		name: "nvidia_gpus",
		desc: "The cards on this instance, and which one is throttling. Every numeric field is also a metric series, but the series is labelled by `gpu_index` and cannot tell you what that card IS -- `name` lives only on this row.\n\nNULL IS \"NVIDIA-SMI DID NOT RETURN IT\", NEVER ZERO. It omits fields per driver version and per card: a consumer card reports no `power_limit`, a passthrough card in a VM reports no `fan_speed`. A 0 would read as \"idle\" or \"drawing no power\" on the one device whose job is to be busy.\n\n`processes` has the same trap in array form: an empty list is an idle GPU, but it is also what a card in MIG mode or inside a container without PID-namespace visibility reports.",
		filters: []inventoryFilter{
			{name: "updated_since", kind: fieldString, desc: "Return only rows whose `updated_at` is at or after this ISO 8601 timestamp. Inclusive, so a row updated in the same instant as the cursor comes back rather than falling through the gap. The ingester touches `updated_at` on every agent tick, so this is a freshness filter rather than a change feed, and there are no tombstones: a row the agent stops reporting is deleted."},
			{name: "stale", kind: fieldBool, desc: "Freshness filter over the collector's 10-minute sync window. `false` returns only rows the agent refreshed inside it -- the set you may read as CURRENT state; `true` returns the rest. The two values partition the collection (a row that never synced counts as stale). Omit for both."},
			{name: "q", kind: fieldString, desc: "Case-insensitive substring match on the card name."},
		},
		fields: []inventoryField{
			{"id", fieldInt, "Row identifier."},
			{"host_id", fieldString, "The instance (host) UUID this row belongs to."},
			{"index", fieldInt, "The nvidia-smi enumeration index, and half the row's identity (the upsert key is host + index). NOT stable across a reboot if cards are added or removed."},
			{"name", fieldString, "The card model as nvidia-smi reports it. Null when not reported."},
			{"temperature", fieldInt, "Degrees Celsius. Null = not reported, not 0."},
			{"fan_speed", fieldInt, "Percent. Null on any card with no controllable fan -- a passthrough card in a VM, or a passively cooled datacentre part. Not 0."},
			{"power_draw", fieldInt, "Watts. Null = not reported, not \"drawing no power\"."},
			{"power_limit", fieldInt, "Watts. Null on consumer cards that do not expose one."},
			{"utilization_gpu", fieldInt, "Percent. Null = not reported, which is NOT an idle GPU."},
			{"utilization_memory", fieldInt, "Percent of memory BANDWIDTH in use -- not memory occupancy."},
			{"memory_used", fieldInt, "Bytes."},
			{"memory_total", fieldInt, "Total framebuffer memory, in bytes. Null when not reported."},
			{"memory_free", fieldInt, "Free framebuffer memory, in bytes. Null when not reported."},
			{"clock_sm", fieldInt, "MHz."},
			{"clock_mem", fieldInt, "MHz."},
			{"processes", fieldJSON, "The compute processes nvidia-smi attributed to this card. An EMPTY ARRAY IS AMBIGUOUS: it is an idle GPU, but it is also what a card in MIG mode or inside a container without PID-namespace visibility reports. Do not read it as \"nothing is using this GPU\". JSON-encoded; decode with `jsondecode()`."},
			{"last_synced_at", fieldString, "Server arrival time of the tick that last refreshed this row (never the agent's clock). Null when the row has never synced."},
			{"stale", fieldBool, "The row has not been refreshed inside the collector's 10-minute window (a NULL `last_synced_at` counts as stale). `false` means safe to read as current state."},
			{"created_at", fieldString, "When this row was first recorded. This is when the agent first happened to report it, not anything an operator would recognize."},
			{"updated_at", fieldString, "When this row was last written. The ingester touches it on every agent tick, so it is a freshness stamp rather than a change feed."},
		},
	},
	{
		name: "fail2ban_jails",
		desc: "The jails on this instance, how many addresses each is holding, and WHICH ADDRESSES. The series can count bans; only this names them.\n\nTWO COUNTERS PER AXIS, ANSWERING DIFFERENT QUESTIONS. `currently_banned` and `currently_failed` are LIVE gauges -- what the jail holds right now. `total_banned` and `total_failed` are CUMULATIVE since fail2ban started, so they only rise and a restart RESETS them; deriving a rate from two polls of the totals is wrong across that restart.\n\n`banned_ips` is best-effort: the agent can read the COUNT without the list, so an empty array on a jail with a non-zero `currently_banned` is possible. Treat the count as authoritative.",
		filters: []inventoryFilter{
			{name: "updated_since", kind: fieldString, desc: "Return only rows whose `updated_at` is at or after this ISO 8601 timestamp. Inclusive, so a row updated in the same instant as the cursor comes back rather than falling through the gap. The ingester touches `updated_at` on every agent tick, so this is a freshness filter rather than a change feed, and there are no tombstones: a row the agent stops reporting is deleted."},
			{name: "stale", kind: fieldBool, desc: "Freshness filter over the collector's 10-minute sync window. `false` returns only rows the agent refreshed inside it -- the set you may read as CURRENT state; `true` returns the rest. The two values partition the collection (a row that never synced counts as stale). Omit for both."},
			{name: "q", kind: fieldString, desc: "Case-insensitive substring match on the jail name."},
		},
		fields: []inventoryField{
			{"id", fieldInt, "Row identifier."},
			{"host_id", fieldString, "The instance (host) UUID this row belongs to."},
			{"name", fieldString, "The jail name, e.g. `sshd`."},
			{"currently_banned", fieldInt, "LIVE gauge -- how many addresses the jail holds right now."},
			{"total_banned", fieldInt, "CUMULATIVE since fail2ban started, so it only ever rises and a restart RESETS it. Do not derive a rate from two polls without handling that."},
			{"currently_failed", fieldInt, "LIVE gauge -- failures currently tracked toward a ban."},
			{"total_failed", fieldInt, "CUMULATIVE since fail2ban started -- see `total_banned`."},
			{"banned_ips", fieldStringList, "The addresses the jail currently holds. Best-effort: the agent can read the COUNT without the list, so this can be empty on a jail with a non-zero `currently_banned`. Treat the count as authoritative."},
			{"active", fieldBool, "The jail is holding at least one ban. NOT a health verdict -- a jail with bans is fail2ban working, not fail2ban failing."},
			{"last_synced_at", fieldString, "Server arrival time of the tick that last refreshed this row (never the agent's clock). Null when the row has never synced."},
			{"stale", fieldBool, "The row has not been refreshed inside the collector's 10-minute window (a NULL `last_synced_at` counts as stale)."},
			{"created_at", fieldString, "When this row was first recorded. This is when the agent first happened to report it, not anything an operator would recognize."},
			{"updated_at", fieldString, "When this row was last written. The ingester touches it on every agent tick, so it is a freshness stamp rather than a change feed."},
		},
	},
	{
		name: "php_fpm_pools",
		desc: "The per-pool process state behind the instance's PHP-FPM view -- which pool ran out of workers, and when it last happened.\n\nREAD `max_children_reached_at`, NOT `max_children_reached`. The counter is CUMULATIVE since php-fpm started, so a non-zero value means \"this has happened at some point\", not \"it is happening now\", and it resets on a reload. `max_children_reached_at` is set only when the counter actually INCREASED between two agent ticks, which makes it the durable exhaustion signal; `children_exhausted` applies the product's 5-minute window to it.\n\nNull gauges are \"the agent did not report this field on the last tick\", never zero: a pool with a null `active_processes` is unknown, not idle.\n\nThis collector is config-driven with no version floor, so `collector.supported` here means \"the agent has not said it cannot\" -- an agent predating the collector answers `true` with an empty list. Check `collector.last_reported_at` and the agent version before concluding the instance runs none.",
		filters: []inventoryFilter{
			{name: "updated_since", kind: fieldString, desc: "Return only rows whose `updated_at` is at or after this ISO 8601 timestamp. Inclusive, so a row updated in the same instant as the cursor comes back rather than falling through the gap. The ingester touches `updated_at` on every agent tick, so this is a freshness filter rather than a change feed, and there are no tombstones: a row the agent stops reporting is deleted."},
			{name: "stale", kind: fieldBool, desc: "Freshness filter over the collector's 10-minute sync window. `false` returns only rows the agent refreshed inside it -- the set you may read as CURRENT state; `true` returns the rest. The two values partition the collection (a row that never synced counts as stale). Omit for both."},
			{name: "q", kind: fieldString, desc: "Case-insensitive substring match on the pool name."},
		},
		fields: []inventoryField{
			{"id", fieldInt, "Row identifier."},
			{"host_id", fieldString, "The instance (host) UUID this row belongs to."},
			{"name", fieldString, "The pool name, as configured in the pool's own php-fpm config."},
			{"process_manager", fieldString, "The pool's process manager mode (`static`, `dynamic`, `ondemand`). Null when not reported."},
			{"active_processes", fieldInt, "Workers currently serving a request."},
			{"idle_processes", fieldInt, "Workers idle right now. **Null means not reported, not 0.**"},
			{"total_processes", fieldInt, "Workers alive right now. **Null means not reported, not 0.**"},
			{"listen_queue", fieldInt, "Requests waiting to be accepted right now."},
			{"max_listen_queue", fieldInt, "High-water mark since php-fpm started."},
			{"max_children_reached", fieldInt, "CUMULATIVE count of times the process manager hit its child ceiling since php-fpm started. Resets on a reload. A non-zero value does NOT mean the pool is exhausted now."},
			{"slow_requests", fieldInt, "Cumulative, same caveat as above."},
			{"accepted_connections", fieldInt, "Cumulative, same caveat as above."},
			{"max_children_reached_at", fieldString, "THE durable exhaustion signal: set only when max_children_reached actually INCREASED between two agent ticks. Null means it has never happened while we were watching."},
			{"queue_saturated", fieldBool, "A request was sitting in the listen queue on the last tick."},
			{"children_exhausted", fieldBool, "max_children_reached_at falls inside the product's 5-minute window. This is the \"pool exhausted right now\" reading."},
			{"saturated", fieldBool, "Either saturation signal, at the product's default thresholds."},
			{"saturation_detail", fieldString, "Which signal(s) fired, e.g. \"listen queue at 12, hit max_children\", or \"healthy\"."},
			{"last_synced_at", fieldString, "When the agent last refreshed this row."},
			{"stale", fieldBool, "True when the agent stopped refreshing this row (outside the 10-minute sync window, or never synced). These tables are only updated while an agent keeps reporting, so a problem row on a dead agent reads as a problem forever -- check this before acting on the state above."},
			{"created_at", fieldString, "When this row was first recorded. This is when the agent first happened to report it, not anything an operator would recognize."},
			{"updated_at", fieldString, "When this row was last written. The ingester touches it on every agent tick, so it is a freshness stamp rather than a change feed."},
		},
	},
	{
		name: "rabbitmq_queues",
		desc: "The per-queue depth and consumer state behind the instance's RabbitMQ view -- which queue is backing up and whether anything is consuming it.\n\nTHE NULL RULE HERE IS THE OPPOSITE OF THE ZFS ONE. A null `messages` or `consumers` reads as ZERO, deliberately, and the derived predicates (`starved`, `backlogged`, `backlog_detail`) are published beside the raw columns: rebuild the rule yourself and you will disagree with the product on exactly the rows that matter.\n\nTHE RATES ARE INSTANTANEOUS, not counters -- a delta between two polls is meaningless. Identity is (`vhost`, `name`): a queue name is unique only within a vhost, so `name` alone can legitimately repeat.\n\nA row can linger: the agent ships a top-N-capped watch set, so a queue dropping out of the cap is indistinguishable from a deleted one and queues are never vanish-pruned. `stale` is the only way a queue leaves this list.\n\nThis collector is config-driven with no version floor, so `collector.supported` here means \"the agent has not said it cannot\".",
		filters: []inventoryFilter{
			{name: "updated_since", kind: fieldString, desc: "Return only rows whose `updated_at` is at or after this ISO 8601 timestamp. Inclusive, so a row updated in the same instant as the cursor comes back rather than falling through the gap. The ingester touches `updated_at` on every agent tick, so this is a freshness filter rather than a change feed, and there are no tombstones: a row the agent stops reporting is deleted."},
			{name: "stale", kind: fieldBool, desc: "Freshness filter over the collector's 10-minute sync window. `false` returns only rows the agent refreshed inside it -- the set you may read as CURRENT state; `true` returns the rest. The two values partition the collection (a row that never synced counts as stale). Omit for both."},
			{name: "q", kind: fieldString, desc: "Case-insensitive substring match on the queue name or its vhost."},
		},
		fields: []inventoryField{
			{"id", fieldInt, "Row identifier."},
			{"host_id", fieldString, "The instance (host) UUID this row belongs to."},
			{"vhost", fieldString, "Part of the identity: a queue name is unique only within a vhost."},
			{"name", fieldString, "The queue name. Unique only within `vhost`, which is the other half of the identity."},
			{"messages", fieldInt, "READY depth -- messages waiting to be delivered. Null reads as 0."},
			{"messages_unacknowledged", fieldInt, "Delivered but not yet acked."},
			{"consumers", fieldInt, "Attached consumers. Null reads as 0, so null with a positive depth is starved."},
			{"publish_rate", fieldFloat, "INSTANTANEOUS messages/second. Not a counter -- do not difference it."},
			{"deliver_rate", fieldFloat, "INSTANTANEOUS messages/second. Not a counter."},
			{"state", fieldString, "The broker's own queue state."},
			{"backlogged", fieldBool, "Ready depth at or above the product's default threshold (1000)."},
			{"starved", fieldBool, "Zero consumers with a positive depth -- the \"workers died\" signal, worth acting on well below any depth threshold."},
			{"backlogged_or_starved", fieldBool, "Either signal."},
			{"backlog_detail", fieldString, "Which signal(s) fired, e.g. \"0 consumers, 90000 messages\"."},
			{"last_synced_at", fieldString, "When the agent last refreshed this row."},
			{"stale", fieldBool, "True when the agent stopped refreshing this row (outside the 10-minute sync window, or never synced). These tables are only updated while an agent keeps reporting, so a problem row on a dead agent reads as a problem forever -- check this before acting on the state above."},
			{"created_at", fieldString, "When this row was first recorded. This is when the agent first happened to report it, not anything an operator would recognize."},
			{"updated_at", fieldString, "When this row was last written. The ingester touches it on every agent tick, so it is a freshness stamp rather than a change feed."},
		},
	},
	{
		name: "rabbitmq_nodes",
		desc: "The broker-node resource state behind the instance's RabbitMQ view. Either alarm raised here blocks publishes BROKER-WIDE, so this is what explains a producer stalling on queues that all look healthy.\n\nBOTH ALARM COLUMNS ARE THREE-VALUED: null is \"the agent did not report it\", not `false`. `alarm` collapses null to false (a missing reading is not evidence of an alarm) and is published beside the raw booleans so the two readings cannot silently disagree.\n\n`fd_percent` / `sockets_percent` are null when the limit is unknown, never 0 -- reading a null as zero would report a node at its file-descriptor ceiling as completely idle.\n\nThis collector is config-driven with no version floor, so `collector.supported` here means \"the agent has not said it cannot\".",
		filters: []inventoryFilter{
			{name: "updated_since", kind: fieldString, desc: "Return only rows whose `updated_at` is at or after this ISO 8601 timestamp. Inclusive, so a row updated in the same instant as the cursor comes back rather than falling through the gap. The ingester touches `updated_at` on every agent tick, so this is a freshness filter rather than a change feed, and there are no tombstones: a row the agent stops reporting is deleted."},
			{name: "stale", kind: fieldBool, desc: "Freshness filter over the collector's 10-minute sync window. `false` returns only rows the agent refreshed inside it -- the set you may read as CURRENT state; `true` returns the rest. The two values partition the collection (a row that never synced counts as stale). Omit for both."},
			{name: "q", kind: fieldString, desc: "Case-insensitive substring match on the node name."},
		},
		fields: []inventoryField{
			{"id", fieldInt, "Row identifier."},
			{"host_id", fieldString, "The instance (host) UUID this row belongs to."},
			{"name", fieldString, "The broker node name, e.g. `rabbit@node1`."},
			{"mem_alarm", fieldBool, "Null means the agent did not report it -- NOT false."},
			{"disk_free_alarm", fieldBool, "Null means the agent did not report it -- NOT false."},
			{"alarm", fieldBool, "Either alarm raised. A null column counts as not-raised here, so this and the raw booleans answer slightly different questions on an unreported row."},
			{"fd_used", fieldInt, "File descriptors in use. Null when not reported."},
			{"fd_total", fieldInt, "File descriptor ceiling. Null when not reported."},
			{"fd_percent", fieldFloat, "Null when fd_total is unknown. NOT 0."},
			{"sockets_used", fieldInt, "Sockets in use. Null when not reported."},
			{"sockets_total", fieldInt, "Socket ceiling. Null when not reported."},
			{"sockets_percent", fieldFloat, "Null when sockets_total is unknown. NOT 0."},
			{"mem_used", fieldInt, "Bytes of memory in use. Null when not reported."},
			{"mem_limit", fieldInt, "The memory high-watermark, in bytes. Null when not reported."},
			{"last_synced_at", fieldString, "When the agent last refreshed this row."},
			{"stale", fieldBool, "True when the agent stopped refreshing this row (outside the 10-minute sync window, or never synced). These tables are only updated while an agent keeps reporting, so a problem row on a dead agent reads as a problem forever -- check this before acting on the state above."},
			{"created_at", fieldString, "When this row was first recorded. This is when the agent first happened to report it, not anything an operator would recognize."},
			{"updated_at", fieldString, "When this row was last written. The ingester touches it on every agent tick, so it is a freshness stamp rather than a change feed."},
		},
	},
	{
		name: "haproxy_backends",
		desc: "The per-backend aggregate rows behind the instance's HAProxy view -- which pool is down, and how many of its members are still serving.\n\n`status` IS NOT A SINGLE WORD. HAProxy writes the member tally and the transition source inline (`UP 1/3`, `MAINT (via web/srv1)`). The raw string is published verbatim because it is what an operator sees; `status_word` carries the normalized leading token -- compare against `status_word`, never against `status`.\n\nTHE THREE BOOLEANS DO NOT PARTITION. `NOLB` is deliberately in none of the up/down/maint sets, so all three read false for it. Do not derive one status from an exhaustive if/else over them. `maint` (MAINT or DRAIN) is neither up nor down.\n\n`servers_summary` is null when the agent sent no tally, never `\"0/0\"`, which would read as a pool with no members at all. `http_4xx` / `http_5xx` / `retries` are CUMULATIVE since the last HAProxy reload, not per-tick deltas.\n\nThis collector is config-driven with no version floor, so `collector.supported` here means \"the agent has not said it cannot\".",
		filters: []inventoryFilter{
			{name: "updated_since", kind: fieldString, desc: "Return only rows whose `updated_at` is at or after this ISO 8601 timestamp. Inclusive, so a row updated in the same instant as the cursor comes back rather than falling through the gap. The ingester touches `updated_at` on every agent tick, so this is a freshness filter rather than a change feed, and there are no tombstones: a row the agent stops reporting is deleted."},
			{name: "stale", kind: fieldBool, desc: "Freshness filter over the collector's 10-minute sync window. `false` returns only rows the agent refreshed inside it -- the set you may read as CURRENT state; `true` returns the rest. The two values partition the collection (a row that never synced counts as stale). Omit for both."},
			{name: "status", kind: fieldString, desc: "Filter by the normalized status word. One of: `UP`, `DOWN`, `MAINT`, `DRAIN`, `NOLB`.", oneOf: []string{"UP", "DOWN", "MAINT", "DRAIN", "NOLB"}},
			{name: "q", kind: fieldString, desc: "Case-insensitive substring match on the backend name."},
		},
		fields: []inventoryField{
			{"id", fieldInt, "Row identifier."},
			{"host_id", fieldString, "The instance (host) UUID this row belongs to."},
			{"name", fieldString, "The backend name, as configured in haproxy."},
			{"status", fieldString, "HAProxy's status field VERBATIM -- it carries the member tally or the transition source inline (\"UP 1/3\", \"MAINT (via web/srv1)\"). Do not compare against this; compare against status_word."},
			{"status_word", fieldString, "The normalized leading token, and the value the status filter matches. Null when the agent reported no status at all."},
			{"up", fieldBool, "Serving traffic. The only positive-health claim here."},
			{"down", fieldBool, "Failed its health check -- a real outage."},
			{"maint", fieldBool, "MAINT or DRAIN: a deliberate operator action, neither up nor down. The three booleans do NOT partition -- NOLB reads false for all three."},
			{"active_servers", fieldInt, "Servers currently UP in this backend. Null when not reported."},
			{"total_servers", fieldInt, "Servers configured in this backend. Null when not reported."},
			{"servers_summary", fieldString, "\"3/5\", or null when the agent sent no tally -- never \"0/0\", which would read as a pool with no members at all."},
			{"sessions_current", fieldInt, "Sessions open right now. Null when not reported."},
			{"sessions_max", fieldInt, "High-water mark."},
			{"session_rate", fieldInt, "Sessions per second, as HAProxy reports it."},
			{"queue_current", fieldInt, "Requests queued waiting for a free server."},
			{"http_4xx", fieldInt, "CUMULATIVE since the last reload, not a per-tick delta."},
			{"http_5xx", fieldInt, "CUMULATIVE since the last reload, not a per-tick delta."},
			{"retries", fieldInt, "CUMULATIVE since the last reload, not a per-tick delta."},
			{"last_synced_at", fieldString, "When the agent last refreshed this row."},
			{"stale", fieldBool, "True when the agent stopped refreshing this row (outside the 10-minute sync window, or never synced). These tables are only updated while an agent keeps reporting, so a problem row on a dead agent reads as a problem forever -- check this before acting on the state above."},
			{"created_at", fieldString, "When this row was first recorded. This is when the agent first happened to report it, not anything an operator would recognize."},
			{"updated_at", fieldString, "When this row was last written. The ingester touches it on every agent tick, so it is a freshness stamp rather than a change feed."},
		},
	},
	{
		name: "haproxy_servers",
		desc: "The per-MEMBER rows behind the instance's HAProxy view -- which server in a pool is down, where the backend row only says the pool is degraded.\n\n`check_status` is what says WHY: it carries the health-check verdict (`L7OK`, `L4CON`, `L7STS/503`). HAProxy runs no checks on a member under maintenance, so an empty value there is \"not checked\", never \"the check passed\".\n\nIDENTITY IS (`backend`, `name`). A server name is unique only within its backend, so `web`/`srv1` and `api`/`srv1` are two different members. The `status` contract is the backend's: compare against `status_word`, and the three booleans do not partition.\n\nThis collector is config-driven with no version floor, so `collector.supported` here means \"the agent has not said it cannot\".",
		filters: []inventoryFilter{
			{name: "updated_since", kind: fieldString, desc: "Return only rows whose `updated_at` is at or after this ISO 8601 timestamp. Inclusive, so a row updated in the same instant as the cursor comes back rather than falling through the gap. The ingester touches `updated_at` on every agent tick, so this is a freshness filter rather than a change feed, and there are no tombstones: a row the agent stops reporting is deleted."},
			{name: "stale", kind: fieldBool, desc: "Freshness filter over the collector's 10-minute sync window. `false` returns only rows the agent refreshed inside it -- the set you may read as CURRENT state; `true` returns the rest. The two values partition the collection (a row that never synced counts as stale). Omit for both."},
			{name: "status", kind: fieldString, desc: "Filter by the normalized status word. One of: `UP`, `DOWN`, `MAINT`, `DRAIN`, `NOLB`.", oneOf: []string{"UP", "DOWN", "MAINT", "DRAIN", "NOLB"}},
			{name: "backend", kind: fieldString, desc: "Return only the members of this backend."},
			{name: "q", kind: fieldString, desc: "Case-insensitive substring match on the server or backend name."},
		},
		fields: []inventoryField{
			{"id", fieldInt, "Row identifier."},
			{"host_id", fieldString, "The instance (host) UUID this row belongs to."},
			{"backend", fieldString, "The owning backend. Part of the identity."},
			{"name", fieldString, "HAProxy's svname. Unique only within the backend."},
			{"status", fieldString, "HAProxy's status field VERBATIM -- it carries the member tally or the transition source inline (\"UP 1/3\", \"MAINT (via web/srv1)\"). Do not compare against this; compare against status_word."},
			{"status_word", fieldString, "The normalized leading token, and the value the status filter matches. Null when the agent reported no status at all."},
			{"up", fieldBool, "Serving traffic. The only positive-health claim here."},
			{"down", fieldBool, "Failed its health check -- a real outage."},
			{"maint", fieldBool, "MAINT or DRAIN: a deliberate operator action, neither up nor down. The three booleans do NOT partition -- NOLB reads false for all three."},
			{"check_status", fieldString, "The health-check verdict behind the status, and the field that says WHY a member is down. HAProxy runs no checks on a member under maintenance, so an empty value is \"not checked\", never \"the check passed\"."},
			{"check_duration", fieldInt, "Milliseconds the last check took."},
			{"weight", fieldInt, "The server's load-balancing weight. Null when not reported."},
			{"sessions_current", fieldInt, "Sessions open on this server right now. Null when not reported."},
			{"last_synced_at", fieldString, "When the agent last refreshed this row."},
			{"stale", fieldBool, "True when the agent stopped refreshing this row (outside the 10-minute sync window, or never synced). These tables are only updated while an agent keeps reporting, so a problem row on a dead agent reads as a problem forever -- check this before acting on the state above."},
			{"created_at", fieldString, "When this row was first recorded. This is when the agent first happened to report it, not anything an operator would recognize."},
			{"updated_at", fieldString, "When this row was last written. The ingester touches it on every agent tick, so it is a freshness stamp rather than a change feed."},
		},
	},
	{
		name: "wireguard_peers",
		desc: "The per-peer tunnel state behind the instance's VPN view -- which tunnel went quiet.\n\nTHE RAW PUBLIC KEY IS NEVER PUBLISHED. Identity is served two other ways: `key_digest` (16 hex chars of SHA-256 -- opaque, stable, survives a rename) and `display_name` (the wg-quick alias if the agent found one, else a short fingerprint). Key your own records on `key_digest`; `display_name` is operator-editable and is a label, not an identifier.\n\nHANDSHAKE AGE ONLY MEANS SOMETHING NEXT TO `keepalive`. WireGuard is silent by design, so an idle peer with NO persistent keepalive can have an arbitrarily old handshake and be perfectly healthy -- alerting on age alone will page for healthy peers.\n\nNULL IS \"NO VERDICT\", NEVER \"0 SECONDS AGO\". `handshake_age_seconds` falls back to `first_seen_at` when there has never been a handshake, so a freshly-added peer reads a small age WITHOUT being active -- read `handshake_active` for \"is this tunnel carrying traffic\".\n\nThis collector is config-driven with no version floor, so `collector.supported` here means \"the agent has not said it cannot\".",
		filters: []inventoryFilter{
			{name: "updated_since", kind: fieldString, desc: "Return only rows whose `updated_at` is at or after this ISO 8601 timestamp. Inclusive, so a row updated in the same instant as the cursor comes back rather than falling through the gap. The ingester touches `updated_at` on every agent tick, so this is a freshness filter rather than a change feed, and there are no tombstones: a row the agent stops reporting is deleted."},
			{name: "stale", kind: fieldBool, desc: "Freshness filter over the collector's 10-minute sync window. `false` returns only rows the agent refreshed inside it -- the set you may read as CURRENT state; `true` returns the rest. The two values partition the collection (a row that never synced counts as stale). Omit for both."},
			{name: "interface", kind: fieldString, desc: "Return only the peers on this WireGuard interface."},
			{name: "q", kind: fieldString, desc: "Case-insensitive substring match on the display name, endpoint or allowed IPs -- deliberately never the public key."},
		},
		fields: []inventoryField{
			{"id", fieldInt, "Row identifier."},
			{"host_id", fieldString, "The instance (host) UUID this row belongs to."},
			{"interface", fieldString, "The WireGuard interface the peer is configured on."},
			{"key_digest", fieldString, "16 hex chars of SHA-256 over the public key: opaque, stable, and the same correlation id the workflow triggers use. Key your records on THIS -- it survives a wg-quick rename. The raw public key is deliberately absent from this payload."},
			{"display_name", fieldString, "The wg-quick `# Name =` alias when the agent found one, else a short key fingerprint. Operator-editable, so a label rather than an identifier."},
			{"fingerprint", fieldString, "8 leading base64 characters of the key plus an ellipsis -- the same short form the dashboard renders, so an operator reading a log line and an operator reading the UI are looking at the same peer. It is DERIVED FROM the public key, not opaque: 48 of its 256 bits. That is enough to identify a peer within one interface and not enough to be the key, but treat it as key-derived rather than as a random handle. `id` is the stable opaque identifier; correlate on that."},
			{"qualified_name", fieldString, "interface/display_name -- a peer name is unique only within an interface."},
			{"endpoint", fieldString, "The peer's real public IP:port as the kernel last saw it. Null before the first handshake, and it moves for a roaming peer."},
			{"allowed_ips", fieldString, "The peer's routed subnets."},
			{"last_handshake_at", fieldString, "Null = never handshaked since we started watching. Also reset by the kernel when an interface is recreated, which the ingester treats as forward-only so a wg-quick restart does not read as every peer going dark."},
			{"handshaked", fieldBool, "Whether a real handshake has ever been recorded."},
			{"handshake_age_seconds", fieldFloat, "Seconds since the last handshake, or since the peer first appeared when it has never handshaked -- so a freshly-added peer reads a small age without being active. Null only when neither anchor exists."},
			{"handshake_active", fieldBool, "A REAL handshake inside a fixed 3-minute window. Requires an actual handshake, so a never-connected peer is never active. This is the \"is the tunnel carrying traffic\" field."},
			{"keepalive", fieldBool, "LOAD-BEARING for reading the handshake fields. WireGuard is silent by design, so an idle peer WITHOUT keepalive can have an arbitrarily old handshake and be perfectly healthy -- alerting on age alone will page for healthy peers."},
			{"persistent_keepalive", fieldInt, "The configured keepalive interval in seconds, when set."},
			{"rx_bytes", fieldInt, "Cumulative bytes received from this peer."},
			{"tx_bytes", fieldInt, "Cumulative bytes sent to this peer."},
			{"first_seen_at", fieldString, "When this peer first appeared. The fallback liveness anchor for a peer that has never handshaked."},
			{"last_synced_at", fieldString, "When the agent last refreshed this row."},
			{"stale", fieldBool, "True when the agent stopped refreshing this row (outside the 10-minute sync window, or never synced). These tables are only updated while an agent keeps reporting, so a problem row on a dead agent reads as a problem forever -- check this before acting on the state above."},
			{"created_at", fieldString, "When this row was first recorded. This is when the agent first happened to report it, not anything an operator would recognize."},
			{"updated_at", fieldString, "When this row was last written. The ingester touches it on every agent tick, so it is a freshness stamp rather than a change feed."},
		},
	},
	{
		name: "qemu_vms",
		desc: "The libvirt domains on a KVM host: which VM is shut off and since when, what it is assigned, and what it is currently using.\n\nTHE METRIC VALUES ARE FRESHNESS-GATED. `cpu_percent` and the five fields beside it are denormalized SAMPLES and come back null once `metrics_fresh` is false, rather than as the last known number -- otherwise a dead agent would leave a VM reading \"42% CPU\" forever. A null there is \"no current sample\", never \"idle\".\n\nTHIS IS THE ONLY COLLECTOR THAT CAN REPORT A DELETION. Everywhere else a row the agent stops reporting is deleted, so a sync built on the list alone cannot see it go. A VM removed from libvirt is TOMBSTONED instead: the row stays with `vanished_at` set and clears itself if the VM comes back. **This data source deliberately does NOT filter tombstones out by default**, even though every dashboard surface does -- hiding them is how a sync silently misses the removal it most needed to see. Set `vanished = false` for parity with the UI.\n\nStaleness is org-parameterized on this collector: it is the ORGANIZATION's offline threshold, not the fixed ten minutes the others use.",
		filters: []inventoryFilter{
			{name: "updated_since", kind: fieldString, desc: "Return only rows whose `updated_at` is at or after this ISO 8601 timestamp. Inclusive, so a row updated in the same instant as the cursor comes back rather than falling through the gap. The ingester touches `updated_at` on every agent tick, so this is a freshness filter rather than a change feed. This collector is the ONE EXCEPTION to the no-tombstone rule: a VM removed from libvirt keeps its row with `vanished_at` set, so a sync CAN see a deletion here."},
			{name: "status", kind: fieldString, desc: "The libvirt domain state, in libvirt's own vocabulary. `unknown` is a real value -- what an unrecognized state code maps to -- and does NOT mean the VM is gone (that is `vanished`). One of: `unknown`, `nostate`, `running`, `shutoff`, `paused`, `shutdown`, `crashed`, `pmsuspended`, `idle`.", oneOf: []string{"unknown", "nostate", "running", "shutoff", "paused", "shutdown", "crashed", "pmsuspended", "idle"}},
			{name: "vanished", kind: fieldBool, desc: "Tombstone filter. `false` returns only VMs still present in libvirt, which is what every dashboard surface shows; `true` returns only the ones that disappeared. **Omitting it returns BOTH, which is this data source's default** and the reason an inventory sync can see a removal here at all."},
			{name: "stale", kind: fieldBool, desc: "Freshness filter, built on the ORGANIZATION's offline threshold rather than a fixed window -- QEMU rows are refreshed on the org's own collection cadence. `false` returns only rows refreshed inside it; `true` returns the rest. Omit for both."},
			{name: "q", kind: fieldString, desc: "Case-insensitive substring match on the VM name or its libvirt UUID."},
		},
		fields: []inventoryField{
			{"id", fieldString, "The row's primary key, which is a UUID -- `qemu_vms` is a `id: :uuid` table. Use `vm_uuid` to address a VM anywhere else in the product; this key is only useful for matching rows between two responses of this API."},
			{"host_id", fieldString, "The instance (host) UUID this row belongs to."},
			{"vm_uuid", fieldString, "The libvirt UUID -- the durable identity, and what the dashboard puts in URLs. Correlate on this, not on `id`."},
			{"vm_name", fieldString, "The libvirt domain name. Null when libvirt reported none; `vm_uuid` is the stable identity."},
			{"status", fieldString, "The libvirt domain state, in libvirt's own vocabulary. `unknown` is a real value -- it is what an unrecognized state code maps to, and means \"we could not classify it\", not \"the VM is gone\" (that is `vanished_at`). One of: `unknown`, `nostate`, `running`, `shutoff`, `paused`, `shutdown`, `crashed`, `pmsuspended`, `idle`."},
			{"state_changed_at", fieldString, "When `status` last CHANGED -- the field that turns \"it is shutoff\" into \"it has been shutoff since 03:12\"."},
			{"vcpu_count", fieldInt, "vCPUs assigned to the domain. Null when not reported."},
			{"memory_assigned_bytes", fieldInt, "Bytes ASSIGNED, not used."},
			{"cpu_percent", fieldFloat, "Freshness-gated: NULL once `metrics_fresh` is false, rather than the last known value. Null is \"no current sample\", never \"idle\"."},
			{"ram_percent", fieldFloat, "Freshness-gated: NULL once `metrics_fresh` is false, rather than the last known value. Null is \"no current sample\", never \"idle\"."},
			{"disk_read_bytes_per_sec", fieldFloat, "Freshness-gated: NULL once `metrics_fresh` is false, rather than the last known value. Null is \"no current sample\", never \"idle\"."},
			{"disk_write_bytes_per_sec", fieldFloat, "Freshness-gated: NULL once `metrics_fresh` is false, rather than the last known value. Null is \"no current sample\", never \"idle\"."},
			{"net_rx_bytes_per_sec", fieldFloat, "Freshness-gated: NULL once `metrics_fresh` is false, rather than the last known value. Null is \"no current sample\", never \"idle\"."},
			{"net_tx_bytes_per_sec", fieldFloat, "Freshness-gated: NULL once `metrics_fresh` is false, rather than the last known value. Null is \"no current sample\", never \"idle\"."},
			{"metrics_fresh", fieldBool, "Whether the denormalized sample is inside its five-minute window. This is the field that makes a null metric value explainable rather than merely absent -- read it before concluding a VM is idle."},
			{"metrics_sampled_at", fieldString, "When the gated values above were last sampled."},
			{"vanished_at", fieldString, "When the VM disappeared from libvirt. A TOMBSTONE, not a deletion: the row is kept for the audit trail and clears itself if the VM comes back. This endpoint does NOT filter these out by default even though every dashboard surface does -- hiding rows is how an inventory sync silently misses a removal. Pass `vanished=false` for parity with the UI."},
			{"vanished", fieldBool, "Convenience form of `vanished_at` being set."},
			{"last_synced_at", fieldString, "Server arrival time of the tick that last refreshed this row (never the agent's clock). Null when the row has never synced."},
			{"stale", fieldBool, "The row has not been refreshed inside the ORGANIZATION's offline threshold -- NOT the fixed ten minutes the other collectors use. QEMU rows are refreshed on the org's own collection cadence, so a fixed window would call a slow-interval org's healthy VMs stale."},
			{"created_at", fieldString, "When this row was first recorded. This is when the agent first happened to report it, not anything an operator would recognize."},
			{"updated_at", fieldString, "When this row was last written. The ingester touches it on every agent tick, so it is a freshness stamp rather than a change feed."},
		},
	},
	{
		name: "proxmox_guests",
		desc: "The VMs and containers on the Proxmox cluster this instance reports -- which guest is stopped and since when, and which node currently holds it.\n\nTHESE ROWS ARE NOT THIS INSTANCE'S. Proxmox inventory is CLUSTER-scoped and organization-owned, and only the cluster's authoritative reporter writes it, so every instance reporting a cluster returns the SAME rows with the same ids. The data source is nested under an instance because that is how a caller REACHES the cluster. Deduplicate on `id` if you read more than one instance in a cluster.\n\nAN INSTANCE WHOSE REPORTER HAS AGED OUT RETURNS AN EMPTY LIST, not the cluster's last known rows. `collector.enabled` stays true in that case, so an empty list there is about reporter freshness rather than configuration.\n\nA GUEST MIGRATES: `vmid` is unique cluster-wide and the row is keyed on cluster + vmid, so `node_name` is where the guest lives right now, not a stable attribute of it. `stale` here is the ORGANIZATION's offline threshold, matching what every guest trigger reads -- NOT the fixed ten minutes the nodes and storages data sources use.",
		filters: []inventoryFilter{
			{name: "updated_since", kind: fieldString, desc: "Return only rows whose `updated_at` is at or after this ISO 8601 timestamp. Inclusive, so a row updated in the same instant as the cursor comes back rather than falling through the gap. The ingester touches `updated_at` on every agent tick, so this is a freshness filter rather than a change feed, and there are no tombstones: a row the agent stops reporting is deleted."},
			{name: "status", kind: fieldString, desc: "Filter by guest state. One of: `unknown`, `stopped`, `running`, `paused`, `suspended`.", oneOf: []string{"unknown", "stopped", "running", "paused", "suspended"}},
			{name: "guest_type", kind: fieldString, desc: "Filter by guest kind. One of: `vm`, `lxc`.", oneOf: []string{"vm", "lxc"}},
			{name: "stale", kind: fieldBool, desc: "Freshness filter, built on the ORGANIZATION's offline threshold here -- matching what every guest trigger reads, and NOT the fixed ten minutes the nodes and storages data sources use. Omit for both."},
			{name: "q", kind: fieldString, desc: "Case-insensitive substring match on the guest name or vmid."},
		},
		fields: []inventoryField{
			{"id", fieldString, "Row identifier."},
			{"proxmox_cluster_id", fieldString, "The cluster these rows belong to. NOT the instance: Proxmox inventory is cluster-scoped, so every instance reporting this cluster returns the same rows with the same ids. Deduplicate on `id` if you poll more than one."},
			{"proxmox_node_id", fieldString, "The node currently hosting the guest. Changes on migration."},
			{"node_name", fieldString, "The hosting node's name, denormalized so a row is legible without a second call. Null only if the node row went missing."},
			{"vmid", fieldString, "The Proxmox id an operator recognizes (\"VM 1042\"). A STRING, because that is how Proxmox reports it and how the row is keyed."},
			{"name", fieldString, "The guest name as Proxmox reports it. Null when unnamed; `vmid` is the identity."},
			{"guest_type", fieldString, "A full VM or an LXC container -- genuinely different things behind one Proxmox API. One of: `vm`, `lxc`."},
			{"status", fieldString, "`unknown` is a real value: it is what an unrecognized Proxmox state maps to, and means \"we could not classify it\", not \"the guest is gone\". One of: `unknown`, `stopped`, `running`, `paused`, `suspended`."},
			{"state_changed_at", fieldString, "When `status` last changed -- the field that turns \"it is stopped\" into \"it has been stopped since 04:10\", and the one the guest-status trigger reads."},
			{"last_synced_at", fieldString, "Server arrival time of the tick that last refreshed this row (never the agent's clock). Null when the row has never synced."},
			{"stale", fieldBool, "Measured against the ORGANIZATION's offline threshold, matching what every guest trigger, the fleet grid and the workflow engine read. This is a DIFFERENT window from the one ProxmoxNode and ProxmoxStorage use (a fixed ten minutes), so the same age can read stale here and fresh there. The divergence is the product's, and the endpoints reproduce it rather than agreeing with each other at the cost of agreeing with the alerts."},
			{"created_at", fieldString, "When this row was first recorded. This is when the agent first happened to report it, not anything an operator would recognize."},
			{"updated_at", fieldString, "When this row was last written. The ingester touches it on every agent tick, so it is a freshness stamp rather than a change feed."},
		},
	},
	{
		name: "proxmox_nodes",
		desc: "The nodes in the Proxmox cluster this instance reports, and which of them the cluster can no longer see.\n\nTHESE ROWS ARE NOT THIS INSTANCE'S. Proxmox inventory is CLUSTER-scoped and organization-owned, so every instance reporting a cluster returns the SAME rows with the same ids. Deduplicate on `id` if you read more than one instance in a cluster. An instance whose reporter has aged out returns an EMPTY LIST, not the cluster's last known rows, with `collector.enabled` still true.\n\n`status = \"offline\"` IS THE CLUSTER'S VIEW of a node, not ours: the surviving nodes cannot see it. That is the signal worth alerting on, and it is distinct from both \"the agent stopped reporting\" (`stale`) and \"we cannot reach the Proxmox API at all\" (the `collector` block).\n\n`stale` here is a fixed 10-minute window -- not the organization threshold the guests data source uses.",
		filters: []inventoryFilter{
			{name: "updated_since", kind: fieldString, desc: "Return only rows whose `updated_at` is at or after this ISO 8601 timestamp. Inclusive, so a row updated in the same instant as the cursor comes back rather than falling through the gap. The ingester touches `updated_at` on every agent tick, so this is a freshness filter rather than a change feed, and there are no tombstones: a row the agent stops reporting is deleted."},
			{name: "status", kind: fieldString, desc: "Filter by the cluster's view of the node. One of: `unknown`, `offline`, `online`.", oneOf: []string{"unknown", "offline", "online"}},
			{name: "stale", kind: fieldBool, desc: "Freshness filter over a fixed 10-minute window -- what the proxmox_node_status trigger reads, and not the organization threshold the guests data source uses. Omit for both."},
			{name: "q", kind: fieldString, desc: "Case-insensitive substring match on the node name."},
		},
		fields: []inventoryField{
			{"id", fieldString, "Row identifier."},
			{"proxmox_cluster_id", fieldString, "The cluster these rows belong to. NOT the instance: Proxmox inventory is cluster-scoped, so every instance reporting this cluster returns the same rows with the same ids. Deduplicate on `id` if you poll more than one."},
			{"name", fieldString, "The PVE node name, which IS that machine's system hostname -- the join key back to an instance."},
			{"status", fieldString, "THE CLUSTER'S VIEW of this node, not ours. `offline` means the surviving nodes cannot see it -- the signal worth alerting on, and distinct from both \"the agent stopped reporting\" (`stale`) and \"we cannot reach the Proxmox API at all\" (the `collector` block). One of: `unknown`, `offline`, `online`."},
			{"last_synced_at", fieldString, "Server arrival time of the tick that last refreshed this row (never the agent's clock). Null when the row has never synced."},
			{"stale", fieldBool, "A FIXED 10-minute window, which is what the proxmox_node_status trigger reads -- NOT the organization threshold the guests endpoint uses. See ProxmoxGuest.stale."},
			{"created_at", fieldString, "When this row was first recorded. This is when the agent first happened to report it, not anything an operator would recognize."},
			{"updated_at", fieldString, "When this row was last written. The ingester touches it on every agent tick, so it is a freshness stamp rather than a change feed."},
		},
	},
	{
		name: "proxmox_storages",
		desc: "The storages on the Proxmox cluster this instance reports.\n\nTHESE ROWS ARE NOT THIS INSTANCE'S. Proxmox inventory is CLUSTER-scoped and organization-owned, so every instance reporting a cluster returns the SAME rows with the same ids. Deduplicate on `id` if you read more than one instance in a cluster. An instance whose reporter has aged out returns an EMPTY LIST, with `collector.enabled` still true.\n\nONE LOGICAL POOL APPEARS ONCE PER NODE, and that is the useful shape rather than duplication: a datacenter-wide storage is listed by every node, and `active` is per node -- a shared NFS mount really can be up on one node and down on another. Grouping by `name` alone collapses exactly the failure worth seeing.\n\n`pool` IS NOT `name`. `name` is the PVE storage id an operator types; `pool` is the backing dataset (`rpool/data`), reported by agent >= 1.11.7 and null on older ones. `zpool_root` is its first segment -- the actual zpool -- and it is what correlates this row to a ZFS pool on the node's own host.",
		filters: []inventoryFilter{
			{name: "updated_since", kind: fieldString, desc: "Return only rows whose `updated_at` is at or after this ISO 8601 timestamp. Inclusive, so a row updated in the same instant as the cursor comes back rather than falling through the gap. The ingester touches `updated_at` on every agent tick, so this is a freshness filter rather than a change feed, and there are no tombstones: a row the agent stops reporting is deleted."},
			{name: "storage_type", kind: fieldString, desc: "Filter by the Proxmox storage driver, e.g. `zfspool`."},
			{name: "active", kind: fieldBool, desc: "Filter by the per-node `active` column. Note this is a different question from `stale`: `active` says the storage is enabled and reachable on that node, `stale` says the row itself is old."},
			{name: "stale", kind: fieldBool, desc: "Freshness filter over a fixed 10-minute window. Omit for both."},
			{name: "q", kind: fieldString, desc: "Case-insensitive substring match on the storage name or pool."},
		},
		fields: []inventoryField{
			{"id", fieldString, "Row identifier."},
			{"proxmox_cluster_id", fieldString, "The cluster these rows belong to. NOT the instance: Proxmox inventory is cluster-scoped, so every instance reporting this cluster returns the same rows with the same ids. Deduplicate on `id` if you poll more than one."},
			{"proxmox_node_id", fieldString, "The node this storage is attached to."},
			{"node_name", fieldString, "The node this row describes the storage ON -- see the schema description."},
			{"name", fieldString, "The PVE storage id an operator types. NOT the backing pool."},
			{"storage_type", fieldString, "The Proxmox storage driver, e.g. `zfspool`, `dir`, `lvmthin`. Null when not reported."},
			{"active", fieldBool, "Enabled and reachable ON THIS NODE. Defaults true, so a row that never reported reads active -- `stale` is what tells you that."},
			{"pool", fieldString, "The backing dataset (\"rpool/data\"), reported by agent >= 1.11.7 and null on older ones. NOT the same as `name`."},
			{"zpool_root", fieldString, "The first segment of `pool` -- the actual zpool, and the key that correlates this row to a ZFS pool on the node's own host. Null when `pool` is null or the storage type has no backing pool."},
			{"zfs_backed", fieldBool, "The storage type is zfspool AND a `zpool_root` resolved."},
			{"last_synced_at", fieldString, "Server arrival time of the tick that last refreshed this row (never the agent's clock). Null when the row has never synced."},
			{"stale", fieldBool, "A fixed 10-minute window, matching `recently_synced` -- see ProxmoxGuest.stale for why this differs from the guests endpoint."},
			{"created_at", fieldString, "When this row was first recorded. This is when the agent first happened to report it, not anything an operator would recognize."},
			{"updated_at", fieldString, "When this row was last written. The ingester touches it on every agent tick, so it is a freshness stamp rather than a change feed."},
		},
	},
}
